In [3]:
import pandas as pd
import numpy as np


In [27]:
training = np.array([
[3, 5, 7, 0],
[2, 6, 4, 1],
[2, 4, 9, 0],
[3, 7, 2, 1],
[4, 9, 1, 1],
[4, 4, 8, 0]
])

In [44]:
class KNNRegressor:
    
    def __init__(self, k):
        self.k = k
    
    def fit(self, X, y):
        self.X = X
        self.y = y
        
    def distance (self, p1, p2):
        return np.linalg.norm(p1-p2)
    
    def predict(self, X):
        distances = []
        for x in self.X:
            distances.append(self.distance(x, X))
        indices = np.argsort(distances)[:self.k]
        return sum(self.y[indices])/self.k


            

In [45]:
model = KNNRegressor(3)
model.fit (training[:, 0:3], training[:, 3])

In [46]:
model.distance(model.X[0, :], model.X[1, :])

3.3166247903554

In [48]:
model.predict([0,0,0])

0.6666666666666666

In [51]:
model1 = KNNRegressor(3)
model1.fit(training[:, 0:2], training[:, 3])

In [52]:
model2 = KNNRegressor(3)
model2.fit(training[:, [0, 2]], training[:, 3])

In [54]:
model3 = KNNRegressor(3)
model3.fit(training[:, [1,2]], training[:, 3])

In [57]:
model1.X

array([[3, 5],
       [2, 6],
       [2, 4],
       [3, 7],
       [4, 9],
       [4, 4]])

In [58]:
model2.X

array([[3, 7],
       [2, 4],
       [2, 9],
       [3, 2],
       [4, 1],
       [4, 8]])

In [59]:
model3.X

array([[5, 7],
       [6, 4],
       [4, 9],
       [7, 2],
       [9, 1],
       [4, 8]])

In [63]:
model3.predict((0,0))

0.6666666666666666